server:
  port: 8072

spring:
  application:
    name: course-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.config.import=optional:configserver:http://localhost:8071
#
#
#eureka.instance.preferIpAddress = true
#eureka.client.registerWithEureka = true
#eureka.client.fetchRegistry = true
#eureka.client.serviceUrl.defaultZone = http://localhost:8070/eureka/
#
#
##########TODO: Move this to a file
#example.property= I AM DEFAULT
#spring.datasource.url = jdbc:postgresql://localhost:5432/course_local
#spring.datasource.username = root
#spring.datasource.password = root